// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID    pgtype.UUID `json:"id"`
	Name  string      `json:"name"`
	Value int32       `json:"value"`
}

type User struct {
	ID       pgtype.UUID `json:"id"`
	Username string      `json:"username"`
	Password string      `json:"password"`
}
