// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID       pgtype.UUID `json:"id"`
	Email    pgtype.Text `json:"email"`
	Password pgtype.Text `json:"password"`
}
